_target_: src.models.linear_regression_module.LinearRegressionLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.simple_linear_net.SimpleLinearNet
  input_size: 10
  output_size: 1

# compile model for faster training with pytorch 2.0
compile: false
